include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = algoc
algoc_C_FILES = list.c dlist.c clist.c stack.c queue.c set.c chtbl.c
algoc_HEADER_FILES = list.h dlist.h clist.h stack.h queue.h set.h chtbl.h

include $(GNUSTEP_MAKEFILES)/library.make
