include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = algoc
algoc_C_FILES = list.c dlist.c clist.c stack.c queue.c set.c chtbl.c \
		ohtbl.c bitree.c traverse.c bistree.c heap.c graph.c \
		issort.c qksort.c mgsort.c
algoc_HEADER_FILES = list.h dlist.h clist.h stack.h queue.h set.h chtbl.h \
		     ohtbl.h bitree.h bistree.h heap.h pqueue.h graph.h \
		     sort.h

include $(GNUSTEP_MAKEFILES)/library.make
