-- TODO: Implement and rename
-- function Work:get_estimate_string()
-- 	local result = ""
-- 	estimates = self.estimates or {}
-- 	for skill, estimate in pairs(estimates) do
-- 		result = result .. string.format("%s: %s, ", skill, estimate)
-- 	end
-- 
-- 	-- Strip trailing comma
-- 	return result:sub(1, -3)
-- end

